[build]
  # Perintah ini akan menginstall dependency di backend, lalu di frontend, baru kemudian build frontend
  command = "cd server && npm install && cd ../client && npm install && CI=false npm run build"
  publish = "client/build"

[functions]
  directory = "server"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
  force = true